[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.0", features = ["mysql"] }
dotenvy = "0.15.7"
shell-words = "1.1.0"
tokio = { version = "1.47.1", features = ["process", "rt", "macros"] }
which = "8.0.0"
